name: Build & Push elasticsearch-s6

on:
  push:
    branches: [main]
    tags: ["ms5.elasticsearch-guide/v*.*.*"]
    paths:
      - "ms5.elasticsearch-guide/**"
      - ".github/workflows/elasticsearch-s6-docker.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKER
    steps:
      - uses: actions/checkout@v4

      - name: Generate versi otomatis
        id: version
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          if [[ "${{ github.ref }}" == refs/tags/ms5.elasticsearch-guide/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/ms5.elasticsearch-guide/v}
            echo "tags=itsanla/elasticsearch-s6:latest,itsanla/elasticsearch-s6:$VERSION" >> $GITHUB_OUTPUT
          else
            echo "tags=itsanla/elasticsearch-s6:latest,itsanla/elasticsearch-s6:sha-$SHORT_SHA" >> $GITHUB_OUTPUT
          fi

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: ./ms5.elasticsearch-guide
          push: true
          tags: ${{ steps.version.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
